---
- hosts: localhost
  connection: local

  collections:
    - vmware.alb

  tasks:

    - name: Debug
      debug:
        msg: "{{ avi_credentials }}"
      tags:
        - debug
        - vs

    - name: Define vip data for AZURE
      set_fact:
        vip_data: "{{ vip_data | default([]) + [{ 'vip_id': 0, 'auto_allocate_floating_ip': 'true', 'auto_allocate_ip': 'true', 'avi_allocated_fip': 'true', 'ipam_network_subnet': {'subnet_uuid': subnet_vip_name, 'subnet': {'mask': subnet_vip_cidr.split('/')[1], 'ip_addr': {'type': 'V4', 'addr': subnet_vip_cidr.split('/')[0]}}}}] }}"
      when:
        - subnet_vip_name is defined
        - subnet_vip_cidr is defined
      tags:
        - vs

    - name: Debug VIP data for Azure
      debug:
        msg: "{{ vip_data }}"
      when:
        - vip_data is defined
      tags:
        - debug
        - vs

    - name: Create vsvip for http VS (Azure)
      vmware.alb.avi_vsvip:
        avi_credentials: "{{ avi_credentials | default(omit) }}"
        api_context: "{{ avi_api_context | default(omit) }}"
        name: "vsvip-{{ item.name }}"
        cloud_ref: "/api/cloud/?name={{ cloud_azure_name }}"
        tenant_ref: "/api/tenant?name={{ item.tenant_ref | default('admin') }}"
#        dns_info:
#          - fqdn: "{{ item.dns_info.0.fqdn | default(item.name + '.' + domain.name) }}"
#            type: "{{ item.dns_info.0.type | default('DNS_RECORD_A') }}"
        vip: "{{ vip_data }}"
      loop: "{{ azure.avi.virtualservices.http }}"
      loop_control:
        label: "{{ item.name }}"
      when:
        - azure.avi.virtualservices.http is defined
      tags:
        - vs

    - name: Create vsvip for dns VS (Azure)
      vmware.alb.avi_vsvip:
        avi_credentials: "{{ avi_credentials | default(omit) }}"
        api_context: "{{ avi_api_context | default(omit) }}"
        name: "vsvip-{{ item.name }}"
        cloud_ref: "/api/cloud/?name={{ cloud_azure_name }}"
        tenant_ref: "/api/tenant?name={{ tenant_ref | default('admin') }}"
#        dns_info:
#          - fqdn: "{{ item.dns_info.0 | default(item.name + '.' + domain.name) }}"
#            type: "{{ item.dns_info.0.type | default('DNS_RECORD_A') }}"
        vip: "{{ vip_data }}"
      loop: "{{ azure.avi.virtualservices.dns }}"
      loop_control:
        label: "{{ item.name }}"
      when:
        - azure.avi.virtualservices.dns is defined
      tags:
        - vs

    - name: get pools
      vmware.alb.avi_api_session:
        avi_credentials: "{{ avi_credentials | default(omit) }}"
        api_context: "{{ avi_api_context | default(omit) }}"
        http_method: get
        timeout: 300
        path: pool
      register: pool_results
      tags:
        - vs

    - name: Create pool without server (Azure)
      vmware.alb.avi_pool:
        avi_credentials: "{{ avi_credentials | default(omit) }}"
        api_context: "{{ avi_api_context | default(omit) }}"
        name: "pool-{{ pool_results.obj.count | int + 1}}"
        cloud_ref: "/api/cloud/?name={{ cloud_azure_name }}"
        tenant_ref: "/api/tenant?name={{ tenant_ref | default('admin') }}"
      tags:
        - vs

    - name: update pool with servers (Azure)
      vmware.alb.avi_pool:
        avi_credentials: "{{ avi_credentials | default(omit) }}"
        api_context: "{{ avi_api_context | default(omit) }}"
        avi_api_patch_op : add
        avi_api_update_method: patch
        name: "pool-{{ cloud_results.obj.count | int + 1}}"
        cloud_ref: "/api/cloud/?name={{ cloud_azure_name }}"
        tenant_ref: "/api/tenant?name={{ tenant_ref | default('admin') }}"
        lb_algorithm: "LB_ALGORITHM_ROUND_ROBIN"
        health_monitor_refs:
          - "/api/healthmonitor?name={{ avi_pool.health_monitor_refs | default('hm1') }}"
        servers:
          - ip:
              addr: "{{ item }}"
              type: 'V4'
      loop: "{{ avi_backend_servers_azure }}"
      when:
        - avi_backend_servers_azure is defined
      tags:
        - vs

    - name: create autoscalepolicy for ASG or Scale Set
      vmware.alb.avi_serverautoscalepolicy:
        avi_credentials: "{{ avi_credentials | default(omit) }}"
        api_context: "{{ avi_api_context | default(omit) }}"
        name: "autoscalepolicyAsg"
        tenant_ref: "/api/tenant?name={{ tenant_ref | default('admin') }}"
        min_size: "{{ min_size | default('2') }}"
        max_size: "{{ max_size | default('2') }}"
        max_scaleout_adjustment_step: "{{ max_scaleout_adjustment_step | default('1') }}"
        max_scalein_adjustment_step: "{{ max_scalein_adjustment_step | default('1') }}"
        scaleout_cooldown: "{{ scaleout_cooldown | default('30') }}"
        scalein_cooldown: "{{ scalein_cooldown | default('30') }}"
      tags:
        - vs
        - asg

    - name: get pools
      vmware.alb.avi_api_session:
        avi_credentials: "{{ avi_credentials | default(omit) }}"
        api_context: "{{ avi_api_context | default(omit) }}"
        http_method: get
        timeout: 300
        path: pool
      register: pool_results
      ignore_errors: yes
      tags:
        - pool
        - vs

    - name: create pool with servers based on Auto Scaling Group
      vmware.alb.avi_pool:
        avi_credentials: "{{ avi_credentials | default(omit) }}"
        api_context: "{{ avi_api_context | default(omit) }}"
        name: "pool-{{ pool_results.obj.count | int + 1}}"
        autoscale_launch_config_ref: "/api/autoscalelaunchconfig?name=default-autoscalelaunchconfig"
        autoscale_policy_ref: "/api/serverautoscalepolicy?name=autoscalepolicyAsg"
        cloud_ref: "/api/cloud/?name={{ cloud_azure_name }}"
        tenant_ref: "/api/tenant?name={{ tenant_ref | default('admin') }}"
        lb_algorithm: "LB_ALGORITHM_ROUND_ROBIN"
        external_autoscale_groups:
          - "{{ scale_set_name }}@${{ azure.rg.name | upper }}"
        application_persistence_profile_ref: "/api/applicationpersistenceprofile?name=System-Persistence-Client-IP"
        health_monitor_refs:
          - "/api/healthmonitor?name=hm1"
      when:
        - scale_set is defined
      tags:
        - pool
        - vs

    - name: Create HTTP Virtualservice (based on vsvip)
      vmware.alb.avi_virtualservice:
        avi_credentials: "{{ avi_credentials | default(omit) }}"
        api_context: "{{ avi_api_context | default(omit) }}"
        name: "{{ item.name }}"
        cloud_ref: "/api/cloud/?name={{ cloud_azure_name }}"
        enabled: "{{ item.enabled | default('true') }}"
        tenant_ref: "/api/tenant?name={{ item.tenant_ref | default('admin') }}"
        application_profile_ref: "/api/applicationprofile/?name={{ item.application_profile_ref | default('System-Secure-HTTP') }}"
        ssl_profile_ref: "/api/sslprofile/?name={{ item.ssl_profile_ref | default('System-Standard') }}"
        ssl_key_and_certificate_refs: "/api/sslkeyandcertificate/?name={{ item.ssl_key_and_certificate_refs | default('System-Default-Cert') }}"
        services: "{{ item.services }}"
        pool_ref: "/api/pool?name={{ item.pool_ref }}"
        enable_rhi: "{{ item.enable_rhi | default('false') }}"
        vsvip_ref: "/api/vsvip/?name=vsvip-{{ item.name }}"
        se_group_ref:  "/api/serviceenginegroup/?name={{ item.se_group_ref | default('Default-Group') }}"
        analytics_policy:
          udf_log_throttle: 10
          metrics_realtime_update:
            duration: 0
            enabled: true
          significant_log_throttle: 0
          client_insights: NO_INSIGHTS
          full_client_logs:
            duration: 30
            throttle: 10
            enabled: true
          all_headers: true
      loop: "{{ azure.avi.virtualservices.http }}"
      when:
        - azure.avi.virtualservices.http is defined
      register: outputVsHttp
      tags:
        - vsHttp
        - vs

    - name: Create DNS Virtualservice
      vmware.alb.avi_virtualservice:
        avi_credentials: "{{ avi_credentials | default(omit) }}"
        api_context: "{{ avi_api_context | default(omit) }}"
        name: "{{ item.name }}"
        application_profile_ref: "/api/applicationprofile/?name={{ item.application_profile_ref | default('System-DNS') }}"
        network_profile_ref: "/api/networkprofile/?name={{ item.network_profile_ref | default('System-UDP-Per-Pkt') }}"
        cloud_ref: "/api/cloud/?name={{ cloud_azure_name }}"
        tenant_ref: "/api/tenant?name={{ item.tenant_ref | default('admin') }}"
        tenant: "{{ item.tenant_ref | default('admin') }}"
        se_group_ref:  "/api/serviceenginegroup/?name={{ item.se_group_ref | default('Default-Group') }}"
        services: "{{ item.services }}"
        vsvip_ref: "/api/vsvip/?name=vsvip-{{ item.name }}"
      loop: "{{ azure.avi.virtualservices.dns }}"
      loop_control:
        label: "{{ item.name }}"
      when: azure.avi.virtualservices.dns is defined
      register: outputVsDns
      tags:
        - vs

    - name: Update system config with first DNS VS
      vmware.alb.avi_systemconfiguration:
        avi_credentials: "{{ avi_credentials | default(omit) }}"
        api_context: "{{ avi_api_context | default(omit) }}"
        avi_api_patch_op : add
        avi_api_update_method: patch
        dns_virtualservice_refs: "/api/virtualservice/?name={{ avi_virtualservice.dns.0.name }}"
      tags:
        - vs
      when:
        - azure.avi.virtualservices.dns.0.name is defined

    - name: Wait for the VS Http to be ready
      vmware.alb.avi_api_session:
        avi_credentials: "{{ avi_credentials | default(omit) }}"
        api_context: "{{ avi_api_context | default(omit) }}"
        http_method: get
        timeout: 300
        path: virtualservice-inventory
        tenant: "{{ item.tenant_ref | default('admin') }}"
      register: statusVs
      until: statusVs.obj.results.0.runtime.oper_status.state == "OPER_UP"
      retries: 120
      delay: 10
      when: azure.avi.virtualservices.http is defined
      ignore_errors: yes
      tags:
        - vs

