---
- hosts: localhost
  connection: local
  gather_facts: no

  collections:
    - vmware.alb

  tasks:

#    - name: Debug
#      debug:
#        msg: "{{ avi_credentials }}"
#      tags:
#        - debug
#      when:
#        - nsxt is defined or lsc is defined

    - name: Create a Cloud connector user for LSC
      no_log: True
      vmware.alb.avi_cloudconnectoruser:
        avi_credentials: "{{ avi_credentials | default(omit) }}"
        api_context: "{{ avi_api_context | default(omit) }}"
        private_key: "{{ lookup('file', '{{ lsc.serviceEngineGroup.private_key_path }}') }}"
        name: credsLsc
      register: lscUserOutput
      ignore_errors: no
      tags:
        - cloud
      when:
        - lsc is defined

#    - name: Debug
#      debug:
#        msg: "{{ lscUserOutput.obj.uuid }}"
#      tags:
#        - debug
#      when:
#        - lsc is defined

    - name: Create a Cloud connector user for NSX-T
      vmware.alb.avi_cloudconnectoruser:
        avi_credentials: "{{ avi_credentials | default(omit) }}"
        api_context: "{{ avi_api_context | default(omit) }}"
        name: creds-nsx
        nsxt_credentials:
          username: "{{ nsx_username }}"
          password: "{{ nsx_password }}"
      register: register_nsx_avi_cloudconnectoruser
      tags:
        - cloud
      when:
        - nsxt is defined
        - nsx_username is defined
        - nsx_password is defined

    - name: Saving NSXT Creds uuid - NSX-T
      set_fact:
        nsx_avi_cloudconnectoruser_uuid: "{{ register_nsx_avi_cloudconnectoruser.obj.uuid }}"
      when:
        - nsxt is defined
        -
#    - name: Debug
#      debug:
#        msg: "{{ nsxt.vcenters_details }}"
#      tags:
#        - debug

    - name: Create a Cloud connector user for NSX-T (vcenter)
      no_log: True
      vmware.alb.avi_cloudconnectoruser:
        avi_credentials: "{{ avi_credentials | default(omit) }}"
        api_context: "{{ avi_api_context | default(omit) }}"
        name: "creds-vcenter-{{ my_idx }}"
        vcenter_credentials:
          username: "{{ item.username }}"
          password: "{{ item.password }}"
      loop: "{{ nsxt.vcenters_details }}"
      loop_control:
        index_var: my_idx
      register: register_vcenters_avi_cloudconnectoruser_uuid
      tags:
        - cloud
      when:
        - nsxt is defined
        - nsxt.vcenters_details is defined

#    - name: Debug
#      debug:
#        msg: "{{ register_vcenters_avi_cloudconnectoruser_uuid }}"
#      tags:
#        - debug

    - name: Saving vCenter Creds uuid in a list - NSX-T
      no_log: True
      set_fact:
        vcenters_avi_cloudconnectoruser_uuids: "{{ vcenters_avi_cloudconnectoruser_uuids | default([]) + [ item.obj.uuid ] }}"
      loop: "{{ register_vcenters_avi_cloudconnectoruser_uuid.results }}"
      when:
        - register_vcenters_avi_cloudconnectoruser_uuid.results is defined

#    - name: Saving NSXT Creds uuid - NSX-T
#      set_fact:
#        nsx_avi_cloudconnectoruser_uuid: "{{ register_nsx_avi_cloudconnectoruser.obj.uuid }}"

#    - name: Debug
#      debug:
#        msg: "{{ nsx_avi_cloudconnectoruser_uuid }}"
#      tags:
#        - debug
#      when:
#        - nsx_avi_cloudconnectoruser_uuid is defined
#
#    - name: Debug
#      debug:
#        msg: "{{ vcenters_avi_cloudconnectoruser_uuids }}"
#      tags:
#        - debug
#      when:
#        - vcenters_avi_cloudconnectoruser_uuids is defined
