---
- hosts: localhost
  connection: local
  gather_facts: no

  vars:
    listNetworkUuid: []

  collections:
    - vmware.alb

  tasks:

    - name: Create Avi DNS provider setting (for OpenStack)
      vmware.alb.avi_ipamdnsproviderprofile:
        avi_credentials: "{{ avi_credentials | default(omit) }}"
        api_context: "{{ avi_api_context | default(omit) }}"
        internal_profile:
          dns_service_domain:
            - domain_name: "{{ domain.name }}"
#              num_dns_ip: 1
              pass_through: true
              record_ttl: 100
          ttl: 300
        name: "{{ dns.name | default('dns-avi')}}"
        type: IPAMDNS_TYPE_INTERNAL_DNS
      when:
        - openstack is defined
        - domain.name is defined
      tags:
        - dns



