---
- hosts: localhost
  gather_facts: no

  vars_files:
    - "vars/params.yml"

#  vars:
#    my_pass: []

  collections:
    - vmware.alb

  tasks:

    - name: Set variable avi_credentials
      set_fact:
        avi_credentials:
          api_version: "{{ avi_version }}"
          controller: "{{ controllerPrivateIps | from_json | first }}"
          password: "{{ avi_password }}"
          username: "{{ avi_username }}"
      tags:
        - creds
      when:
        - avi_version is defined
        - controllerPrivateIps is defined
        - avi_password is defined
        - avi_username is defined

    - name: Debug variable avi_credentials
      debug:
        msg: "{{ avi_credentials }}"
      tags:
        - debug

    - name: Update user admin password
      vmware.alb.avi_useraccount:
        controller: "{{ avi_credentials.controller }}"
        username: "{{ avi_credentials.username }}"
        password: "{{ avi_credentials.password }}"
        old_password: "{{ avi_old_password }}"
        api_version: "{{ avi_credentials.api_version }}"
      ignore_errors: yes
      tags:
        - creds
      when:
        - controller.environment != "AWS"

    - name: Setting up Random password for users
      set_fact:
        my_pass: "{{ my_pass | default([]) +  [ lookup('password', '/dev/null length=4 chars=ascii_lowercase') + '_' + lookup('password', '/dev/null length=4 chars=ascii_uppercase') + '-' + lookup('password', '/dev/null length=4 chars=digits') | upper ] }}"
      loop: "{{ aviUser }}"
      loop_control:
        label: "Configuring {{ item.name }}"
      when:
        - aviUser is defined
      tags:
        - creds
        - password

    # - debug:
    #     msg: "{{ item.0.name }}-{{ item.1 }}"
    #   loop: "{{ aviUser|zip(my_pass)|list }}"
    #   when: my_pass is defined

    - name: user creation
      vmware.alb.avi_user:
        avi_credentials: "{{ avi_credentials }}"
        name: "{{ item.0.name }}"
        obj_username: "{{ item.0.name }}"
        obj_password: "{{ item.1 }}"
        access: "{{ item.0.access }}"
        user_profile_ref: "{{ item.0.user_profile_ref }}"
        is_active: "{{ item.0.is_active }}"
        is_superuser: "{{ item.0.is_superuser }}"
        default_tenant_ref: "{{ item.0.default_tenant_ref }}"
      loop: "{{ aviUser|zip(my_pass)|list }}"
      loop_control:
        label: "Configuring {{ item.0.name }}"
      when:
        - aviUser is defined
      tags:
        - creds

    - name: Change Avi Credentials - with Ansible user
      set_fact:
        avi_credentials: >
                          {'api_version': "{{ avi_version }}",
                           'controller': "{{ controllerPrivateIps | from_json | first }}",
                          'password': "{{ my_pass.0 }}",
                          'username': "{{ aviUser.0.name }}"}
      tags:
        - creds

    - name: save json creds
      copy:
        content: '{"avi_credentials": {{ avi_credentials }} }'
        dest: "{{ controller.aviCredsJsonFile | default('~/.creds.json') }}"
      tags:
        - creds

    - name: Create Tenants
      avi_tenant:
        avi_credentials: "{{ avi_credentials }}"
        api_context: "{{ avi_api_context | default(omit) }}"
        config_settings:
          se_in_provider_context: "{{ item.config_settings | community.general.json_query('se_in_provider_context') }}"
          tenant_access_to_provider_se: "{{ item.config_settings | community.general.json_query('tenant_access_to_provider_se') }}"
          tenant_vrf: "{{ item.config_settings | community.general.json_query('tenant_vrf') }}"
        local: "{{ item.local }}"
        name: "{{ item.name }}"
      loop: "{{ tenants | from_json }}"
      loop_control:
        label: "Configuring tenant called {{ item.name }}"
      when:
        - tenants is defined

    - name: Create Tenants for k8s
      avi_tenant:
        avi_credentials: "{{ avi_credentials }}"
        api_context: "{{ avi_api_context | default(omit) }}"
        config_settings:
          se_in_provider_context: true
          tenant_access_to_provider_se: true
          tenant_vrf: false
        local: true
        name: "{{ item.name }}"
      loop: "{{ k8s_tenants | from_json }}"
      loop_control:
        label: "Configuring tenant called {{ item.name }}"
      when:
        - k8s_tenants is defined

    - name: Create Roles
      vmware.alb.avi_role:
        avi_credentials: "{{ avi_credentials }}"
        api_context: "{{ avi_api_context | default(omit) }}"
        name: "{{ item.name }}"
        privileges: "{{ item.privileges | default(omit) }}"
        filters: "{{ item.filters | default(omit) }}"
        allow_unlabelled_access: "{{ item.allow_unlabelled_access | default(omit) }}"
      loop: "{{ roles | from_json }}"
      loop_control:
        label: "Configuring role called {{ item.name }}"
      when:
        - roles is defined

    - name: Create users
      vmware.alb.avi_user:
        avi_credentials: "{{ avi_credentials }}"
        api_context: "{{ avi_api_context | default(omit) }}"
        name: "{{ item.name }}"
        obj_username: "{{ item.username }}"
        obj_password: "{{ avi_password }}"
        access: "{{ item.access }}"
        user_profile_ref: "{{ item.user_profile_ref }}"
        is_active: true
        is_superuser: "{{ item.is_superuser }}"
        default_tenant_ref: "{{ item.default_tenant_ref }}"
      loop: "{{ users | from_json }}"
      loop_control:
        label: "Configuring user called {{ item.name }}"
      when:
        - users is defined

    - name: Update useraccountprofile called Default-User-Account-Profile with account_lock_timeout to 14400 minutes (10 days)
      avi_useraccountprofile:
        avi_credentials: "{{ avi_credentials }}"
        api_context: "{{ avi_api_context | default(omit) }}"
        avi_api_patch_op : add
        avi_api_update_method: patch
        name: Default-User-Account-Profile
        account_lock_timeout: 14400

    - name: Get main Cluster Information
      vmware.alb.avi_api_session:
        avi_credentials: "{{ avi_credentials }}"
        api_context: "{{ avi_api_context | default(omit) }}"
        http_method: get
        path: cluster
      register: clusterInfo
      tags:
        - cluster

    - name: Debug variable cluster uuid
      debug:
        msg: "{{ clusterInfo['obj'].uuid }}"
      tags:
        - debug

    - name: Debug variable
      debug:
        msg: "{{ controller.cluster }}"
      tags:
        - debug

    - name: Debug variable
      debug:
        msg: "{{ controller.floating_ip }}"
      when:
        - controller.floating_ip is defined
      tags:
        - debug


    - name: Set fact cluster_uuid
      set_fact:
        cluster_uuid: "{{ clusterInfo['obj'].uuid }}"
      when:
        - clusterInfo['obj'].uuid is defined

    - name: Configure Cluster object for static_routes only
      vmware.alb.avi_cluster:
        avi_credentials: "{{ avi_credentials }}"
        api_context: "{{ avi_api_context | default(omit) }}"
        api_version: "{{ avi_credentials.api_version }}"
        nodes:
          - name: "{{ controllerPrivateIps | from_json | first }}"
            ip:
              type: V4
              addr: "{{ controllerPrivateIps | from_json | first }}"
            static_routes: "{{ controller.static_routes | fron_json }}"
        name: cluster-0-1
        uuid: "{{ cluster_uuid }}"
      when:
        - controller.static_routes
      tags:
        - cluster

    - name: Configure Cluster object without ClusterIP - if cluster has been configured
      vmware.alb.avi_cluster:
        avi_credentials: "{{ avi_credentials }}"
        api_context: "{{ avi_api_context | default(omit) }}"
        api_version: "{{ avi_credentials.api_version }}"
        nodes:
          - name: "{{ controllerPrivateIps | from_json | first }}"
            ip:
              type: V4
              addr: "{{ controllerPrivateIps | from_json | first }}"
          - name: "{{ controllerPrivateIps | from_json | community.general.json_query('[1]') }}"
            ip:
              type: V4
              addr: "{{ controllerPrivateIps | from_json | community.general.json_query('[1]') }}"
          - name: "{{ controllerPrivateIps | from_json | last }}"
            ip:
              type: V4
              addr: "{{ controllerPrivateIps | from_json | last }}"
        name: cluster-0-1
        uuid: "{{ cluster_uuid }}"
      when:
        - controller.cluster | bool
        - controller.floating_ip is not defined
        - controller.environment == "vcenter"
        - cluster_uuid is defined
      tags:
        - cluster

    - name: Configure Cluster object with ClusterIP - if cluster has been configured
      vmware.alb.avi_cluster:
        avi_credentials: "{{ avi_credentials }}"
        api_context: "{{ avi_api_context | default(omit) }}"
        api_version: "{{ avi_credentials.api_version }}"
        nodes:
            - name: "{{ controllerPrivateIps | from_json | first }}"
              ip:
                type: V4
                addr: "{{ controllerPrivateIps | from_json | first }}"
            - name: "{{ controllerPrivateIps | from_json | community.general.json_query('[1]') }}"
              ip:
                type: V4
                addr: "{{ controllerPrivateIps | from_json | community.general.json_query('[1]') }}"
            - name: "{{ controllerPrivateIps | from_json | last }}"
              ip:
                type: V4
                addr: "{{ controllerPrivateIps | from_json | last }}"
        name: cluster-0-1
        uuid: "{{ cluster_uuid }}"
        virtual_ip:
            addr: "{{ controller.floating_ip }}"
            type: V4
      when:
        - controller.cluster | bool
        - controller.floating_ip is defined
        - controller.environment == "vcenter"
        - cluster_uuid is defined
      tags:
        - cluster

    - name: "Wait for Controller to be up..."
      uri:
        url: '{{ "https://" + controllerPrivateIps | from_json | first + "/api/cluster/runtime" }}'
        return_content: "yes"
        validate_certs: "no"
      delegate_to: "localhost"
      register: result
      until: "result.content.find('CLUSTER_UP') != -1"
      retries: 30
      delay: 30
      when:
        - controller.cluster | bool
        - controller.environment == "vcenter"
      tags:
        - cluster
    
    - name: sleep for 120 seconds and continue with play - if cluster has been configured
      wait_for: timeout=120
      when:
        - controller.cluster | bool
        - controller.environment == "vcenter"
      tags:
        - cluster

    - name: Wait for the Controller cluster to finish - if cluster has been configured
      vmware.alb.avi_api_session:
        avi_credentials: "{{ avi_credentials }}"
        api_version: "{{ avi_credentials.api_version }}"
        http_method: get
        timeout: 300
        path: cluster/status
      register: statusCluster
      ignore_errors: yes
      until:
        - statusCluster.obj.cluster_state.state == "CLUSTER_UP_HA_ACTIVE"
        - statusCluster.obj.node_states.0.state == "CLUSTER_ACTIVE"
        - statusCluster.obj.node_states.1.state == "CLUSTER_ACTIVE"
        - statusCluster.obj.node_states.2.state == "CLUSTER_ACTIVE"
      retries: 120
      delay: 10
      when:
        - controller.cluster | bool
        - controller.environment == "vcenter"
      tags:
        - cluster


#    - name: sleep for 480 seconds and continue with play - if cluster has been configured
#      wait_for: timeout=480
#      when:
#        - controller.cluster is true
#        - controller.environment == "VMWARE"
#      tags:
#        - cluster

    # - name: Avi credentials
    #   debug:
    #     msg: "{{ avi_credentials }}"
    #   tags:
    #     - creds

#    - name: Configure Cluster without HA with Public Controller IP
#      avi_cluster:
#        avi_credentials: "{{ avi_credentials }}"
#        nodes:
#            - name: "{{ controllerPrivateIps | from_json | first }}"
#              ip:
#                type: V4
#                addr: "{{ controllerPrivateIps | from_json | first }}"
#              public_ip_or_name:
#                addr: "{{ controllerPublicIps.0 }}"
#                type: V4
#        name: cluster-0-1
#        uuid: "{{ cluster_uuid }}"
#      when:
#        - controller.enablePublicIP is defined
#      tags:
#        - cluster

#    - name: sleep for 180 seconds and continue with play - if Public Controller IP has been configured
#      wait_for: timeout=180
#      when:
#        - controller.enablePublicIP is defined
#      tags:
#        - cluster
#
#    - name: Wait for the Controller cluster to be up - if Public Controller IP has been configured
#      avi_api_session:
#        avi_credentials: "{{ avi_credentials }}"
#        http_method: get
#        timeout: 300
#        path: cluster/runtime
#      register: statusCluster
#      ignore_errors: yes
#      until:
#        - statusCluster.obj.cluster_state.state == "CLUSTER_UP_NO_HA" or statusCluster.obj.cluster_state.state == "CLUSTER_UP_HA_ACTIVE"
#      retries: 120
#      delay: 10
#      when:
#        - controller.enablePublicIP is defined
#      tags:
#        - cluster

#    - name: Change Avi Credentials if cluster config has been done - with floating cluster IP - if cluster has been configured
#      set_fact:
#        avi_credentials: >
#                          {'api_version': "{{ avi_version }}",
#                           'controller': "{{ controller.floatingIp }}",
#                           'password': "{{ my_pass.0 }}",
#                           'username': "{{ aviUser.0.name }}"}
#      when:
#        - controller.cluster is true
#        - controller.floatingIp is defined
#        - controller.environment == "VMWARE"
#      tags:
#        - cluster