---
- hosts: localhost
  connection: local
  gather_facts: no

  collections:
    - vmware.alb

  tasks:

    - name: Get Clouds list
      vmware.alb.avi_api_session:
        avi_credentials: "{{ avi_credentials | default(omit) }}"
        api_context: "{{ avi_api_context | default(omit) }}"
        http_method: get
        path: cloud
      register: cloudResults

    - name: retrieve cloud uuid
      no_log: True
      set_fact:
        cloud_nsxt_uuid: "{{ item.uuid }}"
      tags:
        - cloud
        - nsxtApi
      loop: "{{ cloudResults.obj.results }}"
      loop_control:
        label: "{{ item.name }}"
      when:
        - item.name == nsxt.cloud.name

    - name: Create vsvip for dns - NSXT
      vmware.alb.avi_vsvip:
        avi_credentials: "{{ avi_credentials | default(omit) }}"
        api_context: "{{ avi_api_context | default(omit) }}"
        name: "vsvip-{{ item.name }}"
        cloud_ref: "/api/cloud/?name={{ nsxt.cloud.name }}"
        vrf_context_ref: "/api/vrfcontext/?name={{ item.tier1 }}"
        tenant: "{{ item.tenant_ref | default('admin') }}"
        dns_info:
          - fqdn: "{{ item.dns_info.0 | default(item.name + '.' + nsxt.domains.0.name) }}"
            type: "{{ item.dns_info.0.type | default('DNS_RECORD_A') }}"
        vip:
          - auto_allocate_ip: true
            ipam_network_subnet:
              network_ref: "/api/network/?name={{ item.network_ref }}"
              subnet:
                mask: "{{ item.cidr.split('/') | last }}"
                ip_addr:
                  type: "{{ item.type | default('V4') }}"
                  addr: "{{ item.cidr.split('/') | first }}"
      loop: "{{ nsxt.virtual_services | from_json | community.general.json_query('dns') }}"
      loop_control:
        label: "vs {{ item.name }} configured"
      when:
        - nsxt.virtual_services is defined
        - nsxt.cloud.name is defined
        - nsxt.domains is defined
      tags:
        - vsvip
        - vs

    - name: Create vsvip for http - NSXT
      vmware.alb.avi_vsvip:
        avi_credentials: "{{ avi_credentials | default(omit) }}"
        api_context: "{{ avi_api_context | default(omit) }}"
        name: "vsvip-{{ item.name }}"
        cloud_ref: "/api/cloud/?name={{ nsxt.cloud.name }}"
        vrf_context_ref: "/api/vrfcontext/?name={{ item.tier1 }}"
        tenant: "{{ item.tenant_ref | default('admin') }}"
        dns_info:
          - fqdn: "{{ item.dns_info.0 | default(item.name + '.' + nsxt.domains.0.name) }}"
            type: "{{ item.dns_info.0.type | default('DNS_RECORD_A') }}"
        vip:
          - auto_allocate_ip: true
            ipam_network_subnet:
              network_ref: "/api/network/?name={{ item.network_ref }}"
              subnet:
                mask: "{{ item.cidr.split('/') | last }}"
                ip_addr:
                  type: "{{ item.type | default('V4') }}"
                  addr: "{{ item.cidr.split('/') | first }}"
      loop: "{{ nsxt.virtual_services | from_json | community.general.json_query('http') }}"
      loop_control:
        label: "vs {{ item.name }} configured"
      when:
        - nsxt.virtual_services is defined
        - nsxt.cloud.name is defined
        - nsxt.domains is defined
      tags:
        - vsvip
        - vs

    - name: retrieve details for NSXT Group - NSXT
      command: python3 ../python/retrieveNsxtGroups.py "{{ controller.aviCredsJsonFile }}" "{{ cloud_nsxt_uuid }}" "{{ item.name }}"
      ignore_errors: no
      loop: "{{ nsxt.pools  |from_json }}"
      register: register_nsxt_groups_json
      when:
        - controller.aviCredsJsonFile is defined
        - cloud_nsxt_uuid is defined
        - nsxt.pools is defined
        - item.type == "nsx-group-based"
      tags:
        - pool
        - vs

    - name: NSXT Group - Saving Groups detail to variable
      set_fact:
        nsxt_groups: "{{ nsxt_groups | default([]) + [item.stdout | from_json] }}"
      loop: "{{ register_nsxt_groups_json.results }}"
      when:
        - register_nsxt_groups_json.results is defined
        - item.stdout is defined

    - name: Create a list variable for NSXT pool Group only
      set_fact:
        nsxt_pools: "{{ nsxt_pools | default([]) + [item] }}"
      loop: "{{ nsxt.pools | from_json }}"
      when:
        - nsxt.pools is defined
        - item.type == "nsx-group-based"

    - name: create pool based on NSXT group - NSXT
      vmware.alb.avi_pool:
        avi_credentials: "{{ avi_credentials | default(omit) }}"
        api_context: "{{ avi_api_context | default(omit) }}"
        name: "{{ item.0.name }}"
        cloud_ref: "/api/cloud/?name={{ nsxt.cloud.name }}"
        markers: "{{ item.0.markers | default(omit) }}"
        tenant: "{{ item.0.tenant_ref | default('admin') }}"
        lb_algorithm: "{{ item.0.lb_algorithm | default('LB_ALGORITHM_ROUND_ROBIN') }}"
        vrf_ref: "/api/vrfcontext/?name={{ item.0.tier1 }}"
        nsx_securitygroup:
          - "{{ item.1.id }}"
        application_persistence_profile_ref: "/api/applicationpersistenceprofile?name={{ item.0.application_persistence_profile_ref | default('System-Persistence-Client-IP') }}"
        default_server_port: "{{ item.0.default_server_port }}"
        health_monitor_refs:
          - "/api/healthmonitor?name={{ item.0.health_monitor_refs | default('hm1') }}"
      loop: "{{ nsxt_pools | zip(nsxt_groups) }}"
      loop_control:
        label: "pool {{ item.0.name }} configured with nsx_group {{ item.1.name }}"
      when:
        - nsxt_pools is defined
        - nsxt_groups is defined
      tags:
        - pool
        - vs

    - name: Create a list variable for IP based pool only
      set_fact:
        standard_pool: "{{ standard_pool | default([]) + [item] }}"
      loop: "{{ nsxt.pools | from_json }}"
      when:
        - nsxt.pools is defined
        - item.type != "nsx-group-based"

    - name: Create/update pool without server (NSX-T)
      avi_pool:
        avi_credentials: "{{ avi_credentials | default(omit) }}"
        api_context: "{{ avi_api_context | default(omit) }}"
        avi_api_patch_op : add
        avi_api_update_method: patch
        name: "{{ item.0.name }}"
        cloud_ref: "/api/cloud/?name={{ nsxt.cloud.name }}"
        vrf_ref: "/api/vrfcontext/?name={{ item.0.tier1 }}"
        markers: "{{ item.0.markers | default(omit) }}"
        tenant: "{{ item.0.tenant_ref | default('admin') }}"
        default_server_port: "{{ item.0.default_server_port }}"
        lb_algorithm: "{{ item.0.lb_algorithm | default('LB_ALGORITHM_ROUND_ROBIN') }}"
        health_monitor_refs:
          - "/api/healthmonitor?name={{ item.0.health_monitor_refs | default('hm1') }}"
        servers:
          - ip:
              addr: "{{ item.1 }}"
              type: 'V4'
      loop: "{{ standard_pool | subelements('avi_app_server_ips') }}"
      loop_control:
        label: "pool {{ item.0.name }} configured with tier1 {{ item.0.tier1 }} ; server IP: {{ item.1 }}"
      when:
        - standard_pool is defined
      tags:
        - pool
        - vs
      ignore_errors: yes


    - name: Create a list of pool group(s) (vCenter)
      set_fact:
        pool_groups: "{{ pool_groups | default([]) + [item] }}"
      loop: "{{ nsxt.pool_groups | from_json }}"
      when:
        - nsxt.pool_groups is defined
        - nsxt.pool_groups | from_json | length > 0

    - name: Create an empty list of pool group(s)
      set_fact:
        pool_groups: []
      when:
        - nsxt.pool_groups is undefined or nsxt.pool_groups | from_json | length == 0

    - name: Create/update pool group
      vmware.alb.avi_poolgroup:
        avi_credentials: "{{ avi_credentials | default(omit) }}"
        api_context: "{{ avi_api_context | default(omit) }}"
        avi_api_patch_op : add
        avi_api_update_method: patch
        name: "{{ item.0.name }}"
        cloud_ref: "/api/cloud/?name={{ nsxt.cloud.name }}"
        tenant: "{{ item.0.tenant_ref | default('admin') }}"
        members:
          - ratio: "{{ item.1.ratio | default(omit) }}"
            pool_ref: "/api/pool?name={{ item.1.name | default(omit) }}"
      loop: "{{ pool_groups | subelements('members') }}"
      loop_control:
        label: "Configure pool group called {{ item.0.name }} in tenant {{ item.0.tenant_ref | default('admin') }}; pool name: {{ item.1.name }}"
      when:
        - pool_groups is defined
        - nsxt.cloud.name is defined
      tags:
        - pool_group

    - name: Create HTTP Policy(ies)
      community.network.avi_httppolicyset:
        avi_credentials: "{{ avi_credentials | default(omit) }}"
        api_context: "{{ avi_api_context | default(omit) }}"
        name: "{{ item.name }}"
        http_request_policy: "{{ item.http_request_policy | default(omit) }}"
        http_response_policy: "{{ item.http_response_policy | default(omit) }}"
      loop: "{{ httppolicyset | from_json }}"
      loop_control:
        label: "{{ item.name }}"
      when:
        - httppolicyset is defined

    - name: Create DNS Virtualservice
      vmware.alb.avi_virtualservice:
        avi_credentials: "{{ avi_credentials | default(omit) }}"
        api_context: "{{ avi_api_context | default(omit) }}"
        name: "{{ item.name }}"
        vrf_context_ref: "/api/vrfcontext/?name={{ item.tier1 }}"
        application_profile_ref: "/api/applicationprofile/?name={{ item.application_profile_ref | default('System-DNS') }}"
        network_profile_ref: "/api/networkprofile/?name={{ item.network_profile_ref | default('System-UDP-Per-Pkt') }}"
        cloud_ref: "/api/cloud/?name={{ nsxt.cloud.name }}"
        tenant: "{{ item.tenant_ref | default('admin') }}"
        se_group_ref:  "/api/serviceenginegroup/?name={{ item.se_group_ref | default('Default-Group') }}"
        services: "{{ item.services }}"
        vsvip_ref: "/api/vsvip/?name=vsvip-{{ item.name }}"
        analytics_policy:
          udf_log_throttle: 10
          metrics_realtime_update:
            duration: 0
            enabled: true
          significant_log_throttle: 0
          client_insights: NO_INSIGHTS
          full_client_logs:
            duration: 0
            throttle: 10
            enabled: true
          all_headers: true
      loop: "{{ nsxt.virtual_services | from_json | community.general.json_query('dns') }}"
      loop_control:
        label: "Creation of VS DNS called {{ item.name }}"
      when:
        - nsxt.virtual_services is defined
        - nsxt.cloud.name is defined
      tags:
        - vs

    - name: Update system config with first DNS VS - NSXT
      vmware.alb.avi_systemconfiguration:
        avi_credentials: "{{ avi_credentials | default(omit) }}"
        api_context: "{{ avi_api_context | default(omit) }}"
        avi_api_patch_op : add
        avi_api_update_method: patch
        dns_virtualservice_refs: "/api/virtualservice/?name={{ nsxt.virtual_services | from_json | community.general.json_query('dns[*].name | [0]') }}"
      tags:
        - vs
      when:
        - nsxt.virtual_services is defined

    - name: Create HTTP Virtualservice NSXT
      vmware.alb.avi_virtualservice:
        avi_credentials: "{{ avi_credentials | default(omit) }}"
        api_context: "{{ avi_api_context | default(omit) }}"
        name: "{{ item.name }}"
        cloud_ref: "/api/cloud/?name={{ nsxt.cloud.name }}"
        vrf_context_ref: "/api/vrfcontext/?name={{ item.tier1 }}"
        enabled: "{{ item.enabled | default('true') }}"
        tenant: "{{ item.tenant_ref | default('admin') }}"
        markers: "{{ item.markers | default(omit) }}"
        application_profile_ref: "/api/applicationprofile/?name={{ item.application_profile_ref | default('System-Secure-HTTP') }}"
        ssl_profile_ref: "/api/sslprofile/?name={{ item.ssl_profile_ref | default('System-Standard') }}"
        ssl_key_and_certificate_refs: "/api/sslkeyandcertificate/?name={{ item.ssl_key_and_certificate_refs | default('System-Default-Cert') }}"
        services: "{{ item.services }}"
        http_policies: "{{ item.http_policies | default(omit) }}"
        pool_ref: "{{ ('/api/pool?name=' + item.pool_ref) if item.pool_ref is defined else omit }}"
        pool_group_ref: "{{ ('/api/poolgroup?name=' + item.pool_group_ref) if item.pool_group_ref is defined else omit }}"
        enable_rhi: "{{ item.enable_rhi | default('false') }}"
        vsvip_ref: "/api/vsvip/?name=vsvip-{{ item.name }}"
        se_group_ref:  "/api/serviceenginegroup/?name={{ item.se_group_ref | default('Default-Group') }}"
        analytics_policy:
          udf_log_throttle: 10
          metrics_realtime_update:
            duration: 0
            enabled: true
          significant_log_throttle: 0
          client_insights: NO_INSIGHTS
          full_client_logs:
            duration: 0
            throttle: 10
            enabled: true
          all_headers: true
      loop: "{{ nsxt.virtual_services | from_json | community.general.json_query('http') }}"
      loop_control:
        label: "Creation of VS HTTP called {{ item.name }}"
      when:
        - nsxt.virtual_services is defined
        - nsxt.cloud.name is defined
      tags:
        - vsHttp
        - vs

    - name: Wait for the First VS to be ready - NSXT
      vmware.alb.avi_api_session:
        avi_credentials: "{{ avi_credentials | default(omit) }}"
        api_context: "{{ avi_api_context | default(omit) }}"
        http_method: get
        timeout: 300
        path: virtualservice-inventory
      register: register_status_vs
      until: register_status_vs.obj.results.0.runtime.oper_status.state == "OPER_UP"
      retries: 60
      delay: 30
      when:
        - nsxt.virtual_services is defined
        - nsxt.cloud.name is defined
      ignore_errors: yes
      tags:
        - vsHttp
        - vs