---
- hosts: localhost
  connection: local
  gather_facts: no

  collections:
    - vmware.alb

  tasks:

    - name: Set variable avi_credentials
      set_fact:
        avi_credentials:
          api_version: "{{ avi_version }}"
          controller: "{{ controllerPrivateIps | from_json | first }}"
          password: "{{ avi_password }}"
          username: "{{ avi_username }}"
      tags:
        - creds
      when:
        - avi_version is defined
        - controllerPrivateIps is defined
        - avi_password is defined
        - avi_username is defined

    - name: Debug variable avi_credentials
      debug:
        msg: "{{ avi_credentials }}"
      tags:
        - debug

    - name: Create a Cloud connector user for LSC
      no_log: True
      vmware.alb.avi_cloudconnectoruser:
        avi_credentials: "{{ avi_credentials | default(omit) }}"
        api_context: "{{ avi_api_context | default(omit) }}"
        private_key: lookup('file', "{{ lsc.serviceEngineGroup | from_json | community.general.json_query('private_key_path') }}")
        name: credsLsc
      register: lscUserOutput
      ignore_errors: no
      tags:
        - cloud
      when:
        - lsc is defined