---
- hosts: seLsc
  become: true
  gather_facts: no
  become_user: root
  become_method: sudo

  tasks:

    - name: Debug controller IP
      debug:
        msg: "{{ controller_ips | from_json | first }}"
      tags:
        - debug
      when:
        - lsc is defined

    - name: copy keys for avi controller
      copy:
        src: "{{ controller.private_key_path }}"
        dest: ".ssh/{{ controller.private_key_path | basename }}"

    - name: sudo curl command for the controller
      become: true
      shell: |
        curl -ks https://"{{ controller_ips | from_json | first }}":443/api/linux_host_install?username=credsLsc | sudo bash
