---
- hosts: seLsc
  become: true
  gather_facts: no
  become_user: root
  become_method: sudo

  tasks:

    - name: copy keys for avi controller
      copy:
        src: "{{ controller | from_json | community.general.json_query('private_key_path') }}"
        dest: ".ssh/{{ controller | from_json | community.general.json_query('private_key_path') | basename }}"

    - name: sudo curl command for the controller
      become: true
      shell: |
        curl -ks https://"{{ controllerPrivateIps | from_json | first }}":443/api/linux_host_install?username=credsLsc | sudo bash
